### PR TITLE
powershell installer

### PR DESCRIPTION
**Pull request by scottf**
This is a modified version of install.ps1 found here https://github.com/ConnectEverything/client-tools/pull/2
It's modified to only install the cli, either the stable or nightly. It's been discussed about adding the ability to install a specific release tag.

### CODE REVIEW

**Comment by ripienaar** [comment]
Seems fine, as a general comment I think its not good that the code doing nightly builds is in a private repo. I can see all you do is run goreleaser but community cant verify that for themselves or inspect how the things they are installing was built /cc @philpennock

**Comment by philpennock** [comment]
There was some back and forth on whether the new installer stuff would also be installing the client tool for the service offered by Synadia, rather than just open source NATS.io tooling, and some uncertainty as to the direction of the new installers as being focused on open source vs service, so I left the repo private initially.

I have no objections to opening it up.

At this time, everything it installs is open source, and the secrets for managing things are properly secured; the README refers to a few service panels which you need authentication to access, with direct links to account IDs, but I think we can live with that.

**Comment by ripienaar** [comment]
OK, I appreciate it's new, happy to park till the picture is clearer - without it holding up this PR, so as long as we aspire to opening that up I think we're good here.

**Comment by ripienaar** [comment]
Should we merge this?

**Pull request merged**
