### PR TITLE
add {{BODY}} token to access request body within --command

### PR DESCRIPTION
**Pull request by miraculli**
I add a new {{BODY}} token to access the request body within --command 

Additionally I wrote a line about the ENVs that get attached to the spawns cmd.

### CODE REVIEW

**Comment by ripienaar** [comment]
Is this different from the existing "{{.Request}}" support?

**Comment by ripienaar** [comment]
See here https://github.com/nats-io/natscli/blob/3e7b7bef0e4871feea5f8ad55cab3c20fbd29dd4/cli/util.go#L602-L639

**Comment by ripienaar** [comment]
```
$ nats reply x 'received: {{.Request}}'
$ nats req x 'hello world'
received: hello world
```

**Comment by miraculli** [comment]
ah... didn´t know about the `{{.Request}}`
Sorry for the noise.

**Comment by ripienaar** [comment]
All good, if you want you can still add the comments update?

**Comment by miraculli** [comment]
Good morning, 
I just checked `{{.Request}}` but it seems to be different to what I hand in mind with this PR.
The `{{.Request}}` variable doesn't get resolved inside a --command exec like

```
nats reply 'test' --command="echo {{.Request}}"
```


```
nats request test 'heyya'
09:38:57 Sending request on "test"
09:38:57 Received with rtt 43.645593ms
{{.Request}}
```

The reply command should exec a `echo heyya` in this case and the response should be just `heyya`

**Comment by ripienaar** [comment]
Ok. I will fix that. Better it works the same as other places rather then. Will check today

**Comment by ripienaar** [comment]
This should sort it https://github.com/nats-io/natscli/pull/613

**Pull request closed without merging**
