### PR TITLE
Updates to consumer info casing in output

### PR DESCRIPTION
**Pull request by wallyqs**
Some updates to consumer info command

before: 
```
State:

  Last Delivered Message: Consumer sequence: 1 Stream sequence: 1 Last delivery: 14m42s ago
    Acknowledgment floor: Consumer sequence: 1 Stream sequence: 1 Last Ack: 14m42s ago
        Outstanding Acks: 0 out of maximum 1,000
    Redelivered Messages: 0
    Unprocessed Messages: 0
           Waiting Pulls: 0 of maximum 512
```

after:
```
State:

  Last Delivered Message: Consumer sequence: 1 Stream sequence: 1 Last delivery: 14m29s ago
    Acknowledgment Floor: Consumer sequence: 1 Stream sequence: 1 Last ack: 14m29s ago
        Outstanding Acks: 0 out of maximum 1,000
    Redelivered Messages: 0
    Unprocessed Messages: 0
           Waiting Pulls: 0 of maximum 512
```

### CODE REVIEW

**Review by ripienaar — APPROVED** [review]
LGTM

**Comment by wallyqs** [comment]
I was checking just in case but this silly change got reverted here in a following commit: https://github.com/nats-io/natscli/commit/2cc0f1862b5b4a83efc27880380af731632e7ccc#diff-5f4db62e1562fa119614c73fce2b6bc5d8fa55868b7c98cd177c1847a3889158R663

**Comment by ripienaar** [comment]
Hmm, yours is still in main here:

https://github.com/nats-io/natscli/blame/f77374d50d882f73f4cab62b15f4ce8804c7bb8f/cli/consumer_command.go#L663

and the other one is also in main though harder to see where it went back in, I recall seeing it got undone but too much code changes for a nice fix.  

https://github.com/nats-io/natscli/blob/f77374d50d882f73f4cab62b15f4ce8804c7bb8f/cli/consumer_command.go#L663-L665

**Comment by wallyqs** [comment]
ah got it, thanks for checking! should have checked main instead… 😅

**Pull request merged**
