### PR TITLE
support parsing command bodies using standard templates

### PR DESCRIPTION
**Pull request by ripienaar**
Signed-off-by: R.I.Pienaar <rip@devco.net>

### CODE REVIEW

**Comment by miraculli** [comment]
Using `{{.Request}}` within the --command exec also seems to be not working:

```
% nats reply x --command='echo {{.Request}}'
```

```
% nats req x 'hello world'
14:35:32 Sending request on "x"
14:35:32 Received with rtt 44.290153ms
{{.Request}}
```

**Comment by ripienaar** [comment]
not seeing: 

```
% bin/nats reply 'weather.>' --command "curl -s wttr.in/{{.Request}}?format=3" -H Backend:LON
﻿12:36:56 Listening on "weather.>" in group "NATS-RPLY-22"
12:36:58 [#0] Received on subject "weather.lon":

lon
```

```
% bin/nats req weather.lon lon
12:37:39 Sending request on "weather.lon"
12:37:39 Received with rtt 55.871219ms
12:37:39 Backend: LON

lon: ⛅️  +14°C
```

old style token place holders also still work

**Comment by miraculli** [comment]
oh wait... I have to check my binary-version :-(

**Comment by miraculli** [comment]
Yes. your are right... I did the test with the wrong build. sorry for the noise....

**Comment by ripienaar** [comment]
no worries :)

**Pull request merged**
