### PR TITLE
Move audit checks logic to internal package

### PR DESCRIPTION
**Pull request by mprimi**
Refactor `audit analyze` command checks into and into a separate `internal/audit` package.
Also move `archive` to `internal` and include some minor logging improvements.

### CODE REVIEW

**Comment by ripienaar** [comment]
Does this need to be public or can it go in `internal/audit`?

**Comment by mprimi** [comment]
> Does this need to be public or can it go in `internal/audit`?

I suppose that's up to you, and wether you want folks to use this stuff as library or not.
I have a weak preference for `internal`. Fewer users, fewer interrupts for me.
Same for the `archive` package

**Comment by ripienaar** [comment]
Yes let’s start there and go public when we need to. We can’t go the other way once it ships :)

**Review by ripienaar — APPROVED** [review]
LGTM, big improvement

**Comment by mprimi** [comment]
Need to set up commit signing on this new laptop... ⏳

**Pull request merged**
